all: mo
mo: *.po
	msgfmt --output-file=../share/locale/sv/LC_MESSAGES/httpripper.mo httpripper-sv.po
	msgfmt --output-file=../share/locale/he/LC_MESSAGES/httpripper.mo httpripper-he.po
	msgfmt --output-file=../share/locale/es/LC_MESSAGES/httpripper.mo httpripper-es.po
	msgfmt --output-file=../share/locale/cy/LC_MESSAGES/httpripper.mo httpripper-cy.po
	msgfmt --output-file=../share/locale/sk/LC_MESSAGES/httpripper.mo httpripper-sk.po
	msgfmt --output-file=../share/locale/sr/LC_MESSAGES/httpripper.mo httpripper-sr.po
	msgfmt --output-file=../share/locale/el/LC_MESSAGES/httpripper.mo httpripper-el.po
	msgfmt --output-file=../share/locale/pt/LC_MESSAGES/httpripper.mo httpripper-pt.po
	msgfmt --output-file=../share/locale/es/LC_MESSAGES/httpripper.mo es.po
	msgfmt --output-file=../share/locale/ru/LC_MESSAGES/httpripper.mo httpripper-ru.po
	msgfmt --output-file=../share/locale/bs/LC_MESSAGES/httpripper.mo httpripper-bs.po
	msgfmt --output-file=../share/locale/de/LC_MESSAGES/httpripper.mo httpripper-de.po
	msgfmt --output-file=../share/locale/uk/LC_MESSAGES/httpripper.mo httpripper-uk.po
	msgfmt --output-file=../share/locale/zh_TW/LC_MESSAGES/httpripper.mo httpripper-zh_TW.po
	msgfmt --output-file=../share/locale/cs/LC_MESSAGES/httpripper.mo httpripper-cs.po
	msgfmt --output-file=../share/locale/ro/LC_MESSAGES/httpripper.mo httpripper-ro.po
	msgfmt --output-file=../share/locale/fr/LC_MESSAGES/httpripper.mo fr.po
	msgfmt --output-file=../share/locale/nds/LC_MESSAGES/httpripper.mo httpripper-nds.po
	msgfmt --output-file=../share/locale/ms/LC_MESSAGES/httpripper.mo httpripper-ms.po
	msgfmt --output-file=../share/locale/pt_BR/LC_MESSAGES/httpripper.mo httpripper-pt_BR.po
	msgfmt --output-file=../share/locale/eu/LC_MESSAGES/httpripper.mo httpripper-eu.po
	msgfmt --output-file=../share/locale/tr/LC_MESSAGES/httpripper.mo httpripper-tr.po
	msgfmt --output-file=../share/locale/de/LC_MESSAGES/httpripper.mo de.po
	msgfmt --output-file=../share/locale/fi/LC_MESSAGES/httpripper.mo httpripper-fi.po
	msgfmt --output-file=../share/locale/fr/LC_MESSAGES/httpripper.mo httpripper-fr.po
	msgfmt --output-file=../share/locale/te/LC_MESSAGES/httpripper.mo httpripper-te.po
	msgfmt --output-file=../share/locale/nl/LC_MESSAGES/httpripper.mo httpripper-nl.po
	msgfmt --output-file=../share/locale/id/LC_MESSAGES/httpripper.mo id.po
	msgfmt --output-file=../share/locale/id/LC_MESSAGES/httpripper.mo httpripper-id.po
	msgfmt --output-file=../share/locale/pt_BR/LC_MESSAGES/httpripper.mo pt_BR.po
	msgfmt --output-file=../share/locale/th/LC_MESSAGES/httpripper.mo httpripper-th.po
	msgfmt --output-file=../share/locale/da/LC_MESSAGES/httpripper.mo httpripper-da.po
	msgfmt --output-file=../share/locale/it/LC_MESSAGES/httpripper.mo httpripper-it.po
	msgfmt --output-file=../share/locale/sr/LC_MESSAGES/httpripper.mo sr.po
	msgfmt --output-file=../share/locale/bg/LC_MESSAGES/httpripper.mo httpripper-bg.po
	msgfmt --output-file=../share/locale/ca/LC_MESSAGES/httpripper.mo httpripper-ca.po
	msgfmt --output-file=../share/locale/gl/LC_MESSAGES/httpripper.mo httpripper-gl.po
	msgfmt --output-file=../share/locale/hu/LC_MESSAGES/httpripper.mo httpripper-hu.po
	msgfmt --output-file=../share/locale/ar/LC_MESSAGES/httpripper.mo httpripper-ar.po
	msgfmt --output-file=../share/locale/zh_CN/LC_MESSAGES/httpripper.mo httpripper-zh_CN.po
	msgfmt --output-file=../share/locale/pl/LC_MESSAGES/httpripper.mo httpripper-pl.po
	msgfmt --output-file=../share/locale/en_GB/LC_MESSAGES/httpripper.mo httpripper-en_GB.po
*.po: httpripper.pot
	msgmerge -U httpripper-sv.po httpripper.pot
	msgmerge -U httpripper-he.po httpripper.pot
	msgmerge -U httpripper-es.po httpripper.pot
	msgmerge -U httpripper-cy.po httpripper.pot
	msgmerge -U httpripper-sk.po httpripper.pot
	msgmerge -U httpripper-sr.po httpripper.pot
	msgmerge -U httpripper-el.po httpripper.pot
	msgmerge -U httpripper-pt.po httpripper.pot
	msgmerge -U es.po httpripper.pot
	msgmerge -U httpripper-ru.po httpripper.pot
	msgmerge -U httpripper-bs.po httpripper.pot
	msgmerge -U httpripper-de.po httpripper.pot
	msgmerge -U httpripper-uk.po httpripper.pot
	msgmerge -U httpripper-zh_TW.po httpripper.pot
	msgmerge -U httpripper-cs.po httpripper.pot
	msgmerge -U httpripper-ro.po httpripper.pot
	msgmerge -U fr.po httpripper.pot
	msgmerge -U httpripper-nds.po httpripper.pot
	msgmerge -U httpripper-ms.po httpripper.pot
	msgmerge -U httpripper-pt_BR.po httpripper.pot
	msgmerge -U httpripper-eu.po httpripper.pot
	msgmerge -U httpripper-tr.po httpripper.pot
	msgmerge -U de.po httpripper.pot
	msgmerge -U httpripper-fi.po httpripper.pot
	msgmerge -U httpripper-fr.po httpripper.pot
	msgmerge -U httpripper-te.po httpripper.pot
	msgmerge -U httpripper-nl.po httpripper.pot
	msgmerge -U id.po httpripper.pot
	msgmerge -U httpripper-id.po httpripper.pot
	msgmerge -U pt_BR.po httpripper.pot
	msgmerge -U httpripper-th.po httpripper.pot
	msgmerge -U httpripper-da.po httpripper.pot
	msgmerge -U httpripper-it.po httpripper.pot
	msgmerge -U sr.po httpripper.pot
	msgmerge -U httpripper-bg.po httpripper.pot
	msgmerge -U httpripper-ca.po httpripper.pot
	msgmerge -U httpripper-gl.po httpripper.pot
	msgmerge -U httpripper-hu.po httpripper.pot
	msgmerge -U httpripper-ar.po httpripper.pot
	msgmerge -U httpripper-zh_CN.po httpripper.pot
	msgmerge -U httpripper-pl.po httpripper.pot
	msgmerge -U httpripper-en_GB.po httpripper.pot
httpripper.pot: ../httpripper/httpripper.py
xgettext --language=Python --keyword=_ --output=httpripper.pot ../httpripper/httpripper.py
